### ISSUE TITLE
CJB Item Spawner Conflict

### ISSUE THREAD

**Issue by lunaria79** [chsiao58/EvenBetterArtisanGoodIcons#1] opened 2024-04-05 01:29 UTC
Hello! When trying to use [CJB's Item Spawner](https://www.nexusmods.com/stardewvalley/mods/93) with this mod installed, this error occurs. I believe that [Better Chests](https://www.nexusmods.com/stardewvalley/mods/9791/?tab=forum&topic_id=13869356) might also be involved. :
```
[SMAPI] The CJBItemSpawner.Framework.ItemMenu menu crashed while drawing itself. SMAPI will force it to exit to avoid crashing the game.
FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s)
   at BetterArtisanGoodIcons.ArtisanGoodTextureProvider.GetDrawInfo(Object item, Texture2D& textureSheet, Rectangle& mainPosition, Rectangle& iconPosition) in C:\Users\kemok\projects\EvenBetterArtisanGoodIcons\ArtisanGoodTextureProvider.cs:line 98
   at BetterArtisanGoodIcons.ArtisanGoodsManager.GetDrawInfo(Object output, Texture2D& textureSheet, Rectangle& mainPosition, Rectangle& iconPosition) in C:\Users\kemok\projects\EvenBetterArtisanGoodIcons\ArtisanGoodsManager.cs:line 40
   at BetterArtisanGoodIcons.Patches.SObjectPatches.DrawInMenuPatch.Prefix(Object __instance, SpriteBatch spriteBatch, Vector2 location, Single scaleSize, Single transparency, Single layerDepth, Boolean drawStackNumber) in C:\Users\kemok\projects\EvenBetterArtisanGoodIcons\Patches\SObjectPatches\DrawInMenuPatch.cs:line 16
   at StardewValley.Object.drawInMenu_PatchedBy<cat.betterartisangoodicons__furyx639.BetterChests>(Object this, SpriteBatch spriteBatch, Vector2 location, Single scaleSize, Single transparency, Single layerDepth, StackDrawType drawStackNumber, Color color, Boolean drawShadow)
   at StardewValley.Menus.InventoryMenu.draw_PatchedBy<furyx639.BetterChests>(InventoryMenu this, SpriteBatch b, Int32 red, Int32 green, Int32 blue)
   at StardewValley.Menus.InventoryMenu.draw(SpriteBatch b)
   at StardewValley.Menus.ItemGrabMenu.draw(SpriteBatch b)
   at CJBItemSpawner.Framework.ItemMenu.draw(SpriteBatch spriteBatch)
   at StardewModdingAPI.Framework.SModHooks.TryDrawMenu(IClickableMenu menu, Action draw_menu_action)
```
This is the link to the full SMAPI log: https://smapi.io/log/f8f8cf3b2c10497a8df04ee6f8db3158
I was so excited when I saw you uploaded this mod, I cannot wait to see how it develops in the future.

**Comment by chsiao58** [comment] 2024-04-05 23:07
I tried using CJB Item Spawner and Better Chests together with this mod to replicate this issue and I haven't been able to replicate it yet. Have you tried to update Better Chests and Better Crafting as indicated in the log?

If you still have the same issue, send me another log after you updated these two mod.

**Comment by chsiao58** [comment] 2024-04-07 22:18
I finally started to encounter the same problem when I start to update 1.6 crops into this mod. Rather than mod pack conflict, I think the issue might have been the code didn't handle crop source correctly when it comes to crop sprite that's not on springobject sprite sheet. I will take sometime to fix this problem.

Thanks for reporting!

**Comment by lunaria79** [comment] 2024-04-07 23:06
No problem! Good luck on fixing it and thank you for taking your time to try and solve it.

**Comment by chsiao58** [comment] 2024-04-10 19:39
I have update the mod, could you download the update from [Nexus](https://www.nexusmods.com/stardewvalley/mods/22144?tab=description) and see if that solve your issue?

Chances are if you are using any mod that added more artisan good base ingredient it might still be broken. If that's the case I will work on a fix for next update.

**Comment by lunaria79** [comment] 2024-04-11 00:54
I can confirm that it does not work with packs that try to modify items added in to the game.

**Comment by chsiao58** [comment] 2024-04-11 17:19
I have updated the mod to fix some small icon issue that occurred with mod expansion crop. Could you please verify if you are still having the same issue?

The mod is currently running without issue with Stardew Valley Expanded mod, so if you are still having issue it might have been caused by the mod you used to add new crop item, they might not have added item id correctly thus causing the crush.

In any case please let me know how it goes and I again would like to have the newest SMAPI log so I can looking the item that is introduce by the specific mod you are using.

**Comment by lunaria79** [comment] 2024-04-11 23:13
It's fixed, I am no longer experiencing the issue! The exact mod i was using is [Aimon111's Fnacy Artisan Goods BAGI](https://www.nexusmods.com/stardewvalley/mods/15149)

I still am attaching my SMAPI log [here](https://smapi.io/log/c1ac0ff0900a48f28da4eeb17745903a)

**Comment by chsiao58** [comment] 2024-04-12 00:05
That's great! I will close this issue then.

**Closed by chsiao58** 2024-04-12 00:05 UTC
